"""sync remaining models to schema

Revision ID: 562707bbf1f6
Revises: a1b2c3d4e5f6
Create Date: 2026-05-15 16:53:58.574844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '562707bbf1f6'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_trigger_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger_kind', sa.String(), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signal_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_trigger_log_id'), 'market_trigger_log', ['id'], unique=False)
    op.create_index(op.f('ix_market_trigger_log_trigger_kind'), 'market_trigger_log', ['trigger_kind'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('persona', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_persona'), 'chat_messages', ['persona'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_table('chat_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('persona', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('last_message_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'persona', name='uq_chat_summary_user_persona')
    )
    op.create_index(op.f('ix_chat_summaries_id'), 'chat_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_chat_summaries_persona'), 'chat_summaries', ['persona'], unique=False)
    op.create_index(op.f('ix_chat_summaries_user_id'), 'chat_summaries', ['user_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('tax_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_id'), 'entities', ['id'], unique=False)
    op.create_index(op.f('ix_entities_user_id'), 'entities', ['user_id'], unique=False)
    op.create_table('investment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('monthly_core_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_reserve_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('core_symbol', sa.String(), nullable=False),
    sa.Column('core_symbol_label', sa.String(), nullable=False),
    sa.Column('reserve_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('last_monthly_executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_trigger_fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_plans_id'), 'investment_plans', ['id'], unique=False)
    op.create_index(op.f('ix_investment_plans_user_id'), 'investment_plans', ['user_id'], unique=True)
    op.create_table('market_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('suggested_action', sa.String(), nullable=True),
    sa.Column('suggested_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('signal_data', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('telegram_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_alerts_id'), 'market_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_market_alerts_user_id'), 'market_alerts', ['user_id'], unique=False)
    op.create_table('telegram_link_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_telegram_link_codes_id'), 'telegram_link_codes', ['id'], unique=False)
    op.create_index(op.f('ix_telegram_link_codes_user_id'), 'telegram_link_codes', ['user_id'], unique=False)
    op.create_table('telegram_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_index(op.f('ix_telegram_links_id'), 'telegram_links', ['id'], unique=False)
    op.create_index(op.f('ix_telegram_links_user_id'), 'telegram_links', ['user_id'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('initial_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_entity_id'), 'accounts', ['entity_id'], unique=False)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('liabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('lender', sa.String(), nullable=True),
    sa.Column('original_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('monthly_payment', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liabilities_entity_id'), 'liabilities', ['entity_id'], unique=False)
    op.create_index(op.f('ix_liabilities_id'), 'liabilities', ['id'], unique=False)
    op.create_index(op.f('ix_liabilities_user_id'), 'liabilities', ['user_id'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('last4', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('expiry_month', sa.Integer(), nullable=True),
    sa.Column('expiry_year', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_bank_name'), 'cards', ['bank_name'], unique=False)
    op.create_index(op.f('ix_cards_id'), 'cards', ['id'], unique=False)
    op.create_index(op.f('ix_cards_user_id'), 'cards', ['user_id'], unique=False)
    op.create_table('telegram_pending_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('extracted', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_pending_tickets_chat_id'), 'telegram_pending_tickets', ['chat_id'], unique=False)
    op.create_index(op.f('ix_telegram_pending_tickets_id'), 'telegram_pending_tickets', ['id'], unique=False)
    op.create_index(op.f('ix_telegram_pending_tickets_user_id'), 'telegram_pending_tickets', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('billing_cycle', sa.String(), nullable=False),
    sa.Column('next_charge_date', sa.Date(), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.add_column('transactions', sa.Column('account_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'accounts', ['account_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'entities', ['entity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'entity_id')
    op.drop_column('transactions', 'account_id')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_telegram_pending_tickets_user_id'), table_name='telegram_pending_tickets')
    op.drop_index(op.f('ix_telegram_pending_tickets_id'), table_name='telegram_pending_tickets')
    op.drop_index(op.f('ix_telegram_pending_tickets_chat_id'), table_name='telegram_pending_tickets')
    op.drop_table('telegram_pending_tickets')
    op.drop_index(op.f('ix_cards_user_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_bank_name'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_liabilities_user_id'), table_name='liabilities')
    op.drop_index(op.f('ix_liabilities_id'), table_name='liabilities')
    op.drop_index(op.f('ix_liabilities_entity_id'), table_name='liabilities')
    op.drop_table('liabilities')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_entity_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_telegram_links_user_id'), table_name='telegram_links')
    op.drop_index(op.f('ix_telegram_links_id'), table_name='telegram_links')
    op.drop_table('telegram_links')
    op.drop_index(op.f('ix_telegram_link_codes_user_id'), table_name='telegram_link_codes')
    op.drop_index(op.f('ix_telegram_link_codes_id'), table_name='telegram_link_codes')
    op.drop_table('telegram_link_codes')
    op.drop_index(op.f('ix_market_alerts_user_id'), table_name='market_alerts')
    op.drop_index(op.f('ix_market_alerts_id'), table_name='market_alerts')
    op.drop_table('market_alerts')
    op.drop_index(op.f('ix_investment_plans_user_id'), table_name='investment_plans')
    op.drop_index(op.f('ix_investment_plans_id'), table_name='investment_plans')
    op.drop_table('investment_plans')
    op.drop_index(op.f('ix_entities_user_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_chat_summaries_user_id'), table_name='chat_summaries')
    op.drop_index(op.f('ix_chat_summaries_persona'), table_name='chat_summaries')
    op.drop_index(op.f('ix_chat_summaries_id'), table_name='chat_summaries')
    op.drop_table('chat_summaries')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_persona'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_market_trigger_log_trigger_kind'), table_name='market_trigger_log')
    op.drop_index(op.f('ix_market_trigger_log_id'), table_name='market_trigger_log')
    op.drop_table('market_trigger_log')
    # ### end Alembic commands ###
